export const VIEW_ITEM = "VIEW_ITEM"
export const STOP_VIEW_ITEM = "STOP_VIEW_ITEM"
export const SET_ITEMS = "SET_ITEMS"
export const SET_FILTER = "SET_FILTER"
export const ADD_ITEM = "ADD_ITEM"
export const DELETE_ITEM = "DELETE_ITEM"
export const SET_TYPE = "SET_TYPE"